### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by brupdk** [cybercdh/cnames#1]
### Error ###

PS C:\> cnames github.com                                                                                                                                                                       panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0xe82d69]

goroutine 6 [running]:
main.main.func1()
        C:/Users/USER/go/pkg/mod/github.com/cybercdh/cnames@v0.0.0-20200304125103-103bf96f3f1d/main.go:36 +0x109
created by main.main
        C:/Users/USER/go/pkg/mod/github.com/cybercdh/cnames@v0.0.0-20200304125103-103bf96f3f1d/main.go:31 +0x13e

![Screenshot 2023-02-10 005438](https://user-images.githubusercontent.com/84624737/217917011-f34c99f4-8594-4389-9cca-0c2c6e72546c.png)

**Comment by cybercdh** [comment]
Thanks for the issue. I wrote this in a hurry a while ago. I believe this is now fixed in the latest set of commits.
